### ISSUE TITLE
Packages for Ubuntu/Centos

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tradeparser#1]
Need make packages for Ubuntu/Centos and push them to repository.

**Comment by knazarov** [comment]
@zloidemon why do you need packages for this module?
It's actually parsing a data format of one of our customers. I don't think it will be useful as-is.

**Comment by zloidemon** [comment]
It is useful to parse ISO currency codes as example. But if it is so specifically why code has opened?

**Comment by knazarov** [comment]
To be honest, we just don't have enough private repos, and this code frankly doesn't constitute any significant intellectual property. Feel free to use as an example of how to implement a fast XML parser in Tarantool :)

**Comment by filonenko-mikhail** [comment]
I think such discussion is obsolete. Gently closing. Feel free to reopen.
