### ISSUE TITLE
Can't parse xmls with the standard declaration <?xml version="1.0" encoding="utf-8"?> 

### ISSUE THREAD

**Issue by makorne** [tarantool/tradeparser#3]
RapidXml itself can read such xmls : http://gist.github.com/JSchaenzle/2726944

```
test_xml([[
<xml>
</xml>]],
'[]')

test_xml([[
<?xml version="1.0" encoding="utf-8"?>
</xml>]],
'[]')
```

taranrtool test.lua

```
ok - xml: []
test.lua:17: expected element name
```

17  local parsed = tradeparser.parse(str, path)

**Comment by filonenko-mikhail** [comment]
Unfortunately no capacity to resolve such issue. Gently closing. Feel free to reopen.
